kind: pipeline
type: docker
name: default


   
steps:
- name: test
  image: alpine
  commands:
  #- echo "$VAULT_ADDR"
  - echo USERNAME
  - echo "PASSWORD"
  # environment:
  #   USERNAME:
  #     from_secret: username
  #   PASSWORD:
  #     from_secret: password

# ---
# kind: secret
# name: username
# get:
#   path: secrets/data/docker
#   name: username

# ---
# kind: secret
# name: password
# get:
#   path: secrets/data/docker
#   name: password